// Code generated by mockery (hand-written, compatible). DO NOT EDIT BY TOOL.

package mocks

import (
	context "context"

	"eidtemplate/internal/business/domain"
	repointerface "eidtemplate/internal/datasources/repositories/interface"

	mock "github.com/stretchr/testify/mock"
)

// WalletRepository is a mock of the repointerface.WalletRepository type.
type WalletRepository struct {
	mock.Mock
}

func (_m *WalletRepository) OpenOrGetAccount(ctx context.Context, actorSubject, ownerType, ownerID string) (domain.WalletAccount, error) {
	ret := _m.Called(ctx, actorSubject, ownerType, ownerID)
	return ret.Get(0).(domain.WalletAccount), ret.Error(1)
}

func (_m *WalletRepository) GetAccountByOwner(ctx context.Context, actorSubject, ownerType, ownerID string) (domain.WalletAccount, error) {
	ret := _m.Called(ctx, actorSubject, ownerType, ownerID)
	return ret.Get(0).(domain.WalletAccount), ret.Error(1)
}

func (_m *WalletRepository) Deposit(ctx context.Context, actorSubject string, in repointerface.WalletDepositInput) (domain.WalletTxn, error) {
	ret := _m.Called(ctx, actorSubject, in)
	return ret.Get(0).(domain.WalletTxn), ret.Error(1)
}

func (_m *WalletRepository) Withdraw(ctx context.Context, actorSubject string, in repointerface.WalletWithdrawInput) (domain.WalletTxn, error) {
	ret := _m.Called(ctx, actorSubject, in)
	return ret.Get(0).(domain.WalletTxn), ret.Error(1)
}

func (_m *WalletRepository) ListTransactions(ctx context.Context, actorSubject, accountID string, offset, limit int) ([]domain.WalletTxn, error) {
	ret := _m.Called(ctx, actorSubject, accountID, offset, limit)
	var r0 []domain.WalletTxn
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.WalletTxn)
	}
	return r0, ret.Error(1)
}

func (_m *WalletRepository) ActiveFeeRule(ctx context.Context, txnType, ownerType, channel string) (*domain.FeeRule, error) {
	ret := _m.Called(ctx, txnType, ownerType, channel)
	var r0 *domain.FeeRule
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.FeeRule)
	}
	return r0, ret.Error(1)
}

func (_m *WalletRepository) MembershipRole(ctx context.Context, subject, orgID string) (string, error) {
	ret := _m.Called(ctx, subject, orgID)
	return ret.String(0), ret.Error(1)
}

func (_m *WalletRepository) Transfer(ctx context.Context, actorSubject string, in repointerface.WalletTransferInput) (domain.WalletTxn, error) {
	ret := _m.Called(ctx, actorSubject, in)
	return ret.Get(0).(domain.WalletTxn), ret.Error(1)
}

func (_m *WalletRepository) Hold(ctx context.Context, actorSubject string, in repointerface.WalletHoldInput) (domain.AccountHold, error) {
	ret := _m.Called(ctx, actorSubject, in)
	return ret.Get(0).(domain.AccountHold), ret.Error(1)
}

func (_m *WalletRepository) ReleaseHold(ctx context.Context, actorSubject, accountID, holdID string) error {
	ret := _m.Called(ctx, actorSubject, accountID, holdID)
	return ret.Error(0)
}

func (_m *WalletRepository) Reverse(ctx context.Context, actorSubject, accountID, txnID string) (domain.WalletTxn, error) {
	ret := _m.Called(ctx, actorSubject, accountID, txnID)
	return ret.Get(0).(domain.WalletTxn), ret.Error(1)
}

func (_m *WalletRepository) SettleHold(ctx context.Context, actorSubject, accountID, holdID string, captureMinor *int64) (domain.WalletTxn, error) {
	ret := _m.Called(ctx, actorSubject, accountID, holdID, captureMinor)
	return ret.Get(0).(domain.WalletTxn), ret.Error(1)
}

func (_m *WalletRepository) GatewayDeposit(ctx context.Context, in repointerface.WalletGatewayDepositInput) (string, error) {
	ret := _m.Called(ctx, in)
	return ret.String(0), ret.Error(1)
}

func (_m *WalletRepository) UpsertOwnerProfile(ctx context.Context, subject string, p domain.WalletOwnerProfile) error {
	ret := _m.Called(ctx, subject, p)
	return ret.Error(0)
}
